### PR TITLE
Support no_std

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

# What I have changed

- Support `no_std`
- Move all tests to the tests directory

### CODE REVIEW

**Comment by Nemo157** [comment]
Awesome, thanks a lot for this. I want to make one more release of the 0.2 versions to get the error deprecation then I'll merge this and start on a 0.3 version including it.

**Comment by koushiro** [comment]
@Nemo157 Maybe we can upgrade minimum supported rustc version (how about 1.31) on version 0.2 or version 0.3.

**Comment by Nemo157** [comment]
Yep, my plan is to remove the minimum version policy and only support latest stable. So, if you feel like switching to edition 2018 for the easier way to support `no_std` I'd be for that.

I think it would also be good to split off an `alloc` feature, I think it should be possible to support the APIs that take in a pre-allocated output without it.

**Comment by koushiro** [comment]
Awesome, that sounds good

**Comment by koushiro** [comment]
BTW, I think adding format check is good choice in new version.

**Comment by Nemo157** [comment]
I hope you don't mind I took the liberty of cherry-picking your changes and splitting them across #35 and #36, moving the tests was very helpful for migrating the code to a modern clippy. Again, thanks a lot for this!

**Pull request closed without merging**
