### PR TITLE
Replace libtest with criterion

### PR DESCRIPTION
**Pull request by koushiro**

### CODE REVIEW

**Comment by Nemo157** [comment]
Nice, I've been meaning to look into criterion.

You could also have clippy run on the benchmarks as well now that they're stable code by changing the script to:

```
    - cargo clippy --all -- -D warnings
    - cargo clippy --all --all-features -- -D warnings
```

r=me with or without that change.

bors delegate+

**Comment by Nemo157** [comment]
Whoops, should be `--all-targets` instead of `--all`

**Comment by koushiro** [comment]
Updated, PTAL again @Nemo157  :)

**Comment by Nemo157** [comment]
bors r+

Thanks!

**Pull request merged**
